### ISSUE TITLE
Add a license?

### ISSUE THREAD

**Issue by m7a** [lyarbean/xxhash-ada#1]
Hello,

I am interested in incorporating this function into a newly created program. However, I could not find any license attached to the files.

What license is `xxhash-ada` available under?

Thanks in advance and kind regards,
Linux-Fan, Ma_Sys.ma (@m7a)

**Comment by lyarbean** [comment]
License file is added  #2

**Comment by m7a** [comment]
Thank you very much for the quick response! This issue is solved :)
